### ISSUE TITLE
Problem When I try to reproduce your work.

### ISSUE THREAD

**Issue by xzhatgeek** [gsndr/RENOIR#1]
I am sorry, when i try to reproduce your work on provided dataset the parameters of triplet doesn't update in some case. Also the performance of triplet is much worse than it was claimed in the paper and i have no idea how to solve this problem.

**Comment by gsndr** [comment]
Hi,
Thanks for your interesting, I upload some new versions of files.
In addition, I tried to reproduce the experiments and my results are the same of the paper (table 8)
To reproudce the work you must:
1) download the  preprocessed datasets from here: https://drive.google.com/drive/folders/1jLb9I80w16IU_AkWr9H5e7vTOcypQsLw?usp=sharing
2) download the models from here: https://drive.google.com/drive/folders/1jLb9I80w16IU_AkWr9H5e7vTOcypQsLw?usp=sharing
3) Setting the RENOIR.conf file as:
```
    N_CLASSES = 2
    PREPROCESSING1 = 0  #if set to 1 code execute preprocessing phase on original date
    LOAD_AUTOENCODER_N = 1 #if 1 the autoencoder for normal items  is loaded from models folder
    LOAD_AUTOENCODER_A = 1 #if 1 the autoencoder for attacks items  is loaded from models folder
    LOAD_NN = 1  #if 1 the classifier is loaded from models folder
    VALIDATION_SPLIT #the percentage of validation set used to train models
```
4) Run the code with  the command:
python main.py KDDCUP99 (name of dataset)

To reproduce the same results of the work you must use my learned models, otherwise the computation of the deep neural network can reports differents results because neural network algorithms are stochastic. They make use of randomness, that is the initializing to random weights, and in turn the same network trained on the same data can produce different results. In addition, the bayesian optimization can produce different best model.

I hope that I solved the problem.

**Comment by xzhatgeek** [comment]
Thank you for your response. I've tried the new src-code and the original one. The comparison results showed that the problem i mentioned do exist in original src-code. For the new src-code, the performance is similar to the one claimed in the paper.
